### ISSUE TITLE
Mean velocity profiles in wind driven shear cases

### ISSUE THREAD

**Issue by katsmith133** [vanroekel/MPAS-Model#22]
There are still some outstanding issues related to shear cases for the model. For example, here is a comparison for a wind-buoyancy driven case (-5 W/m2 cooling + 0.01 surface wind stress) at 48, 72, and 96 hours (LES = solid lines, ADC = dashed lines).
![Screen Shot 2021-07-13 at 10 06 52 AM](https://user-images.githubusercontent.com/5370137/125506107-6fd31829-411c-4288-b733-d8813032c2c4.png)
The primary issue I am concerned about is that the zonal velocities (u) are very low, about an order of magnitude too low. The wind stress seems to be approx. correct (uw at the surface is in agreement with the LES) and so does the heat flux (though there is a tiny bit too much mixing in the temp profile), but yet the velocities are still too low in the primary wind direction (u). I have been playing around with parameter values and while this might change the shape of the velocity profiles a bit, I could not find a fix for the magnitude issue. So I don't think its just a tuning issue, more so something with the model (either a bug or something missing from the budgets?). Any thoughts on why this might be would be helpful...

Other notes/thoughts: 
- `w2` and `vw` do seem a bit large here
- `w3` was not outputted for this LES case, so it is plotted as zero

**Comment by katsmith133** [comment]
Additional note:
 - `u` is not only an order of magnitude too small, but also largely confined to the surface for the ADC model:
 
![Screen Shot 2021-07-13 at 12 58 07 PM](https://user-images.githubusercontent.com/5370137/125509694-d72bbcbe-f699-42c8-9dd9-bc50121dbfba.png)

**Comment by BrodiePearson** [comment]
Hi Kat, these are really interesting plots and the point you make about uw being ok while U is very poor is intriguing. I will have a think about that and take another look at the code.

- Another thing that surprised me was that the LES reminds me more of an Equator (zero f) case, since uw varies linearly with depth, vw is essentially zero, and u is accelerating uniformly in time creating an entraining shear that at the mixed layer base (although I would also expect v to be zero in that case).
- In contrast, the ADC results look like a f-plane case: vw appears below the surface as the Ekman layer rotates the stress, u is steady-ish in time. **Were both the LES and MPAS run with non-zero or zero f?**

**Comment by katsmith133** [comment]
@BrodiePearson I had that exact same thought as soon as I posted this and am now seeing if that is the case. Both the ADC model and the LES have f = 1.0e-4 in their input files, but if I run the ADC model with f = 0, then I get a much more appropriate `u` profile that matches the LES better. So even though f was set to 1.0e-4 in the LES input file, somehow that did not actually propagate through into the simulation?

**Comment by katsmith133** [comment]
Closing this issue, as it turns out to not actually be an issue...
